@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Acme-Lexical-Thief/project>
	deps:runtime-requirement         [ deps:on "Keyword::Simple 0"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "PadWalker 0"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::Fatal 0"^^deps:CpanId ].

